language: python
python: "3.6"
# command to install dependencies
install:
  - pip install -U pytest
  - pip install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl
  - pip install torchvision
  - pip install .
# command to run tests
script: pytest